version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: obscura-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ".:/app"
    networks:
      - "obscura_65_backend_obscura"
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    image: obscura-envoy-proxy
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      - "obscura_65_backend_obscura"

networks:
  obscura_65_backend_obscura:
    external: true
