version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: obscura-frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ".:/app"
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    image: obscura-envoy-proxy
    ports:
      - "8080:8080"