version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: obscura-frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ".:/app"